### ISSUE TITLE
Forgot password UI

### ISSUE THREAD

**Issue by harshjohar** [PEC-CSS/website#105]

**Comment by aadityavvij** [comment]
can i contribute on this one?

**Comment by harshjohar** [comment]
Sure, make it quick

**Comment by aadityavvij** [comment]
![Screenshot 2023-11-05 124453](https://github.com/PEC-CSS/website/assets/119474270/f7decaba-fc3c-4a25-93fd-d503e0a3dffd)
Do I need to make only this page?
or another page to reset the password

**Comment by harshjohar** [comment]
This page and the page which will be opened to enter new password. Url of that page shall be `forgot-password/change-password?token=` this token will come from the email, you dont have to worry about it. Just create the ui at right place.
