### ISSUE TITLE
error pop up while trying to register

### ISSUE THREAD

**Issue by harasees-singh** [PEC-CSS/website#130]
<img width="661" alt="image" src="https://github.com/PEC-CSS/website/assets/76965050/e50230b4-125f-441a-9ede-14bcd55a7c50">

NOTE: error spotted on localhost only (on main branch)

**Comment by harshjohar** [comment]
What exactly is happening? Please answer the following points:
- is the registration successful?
- is the mail getting sent properly?
- is the user able to login even after this error?
- was the user already present in db?

**Comment by harasees-singh** [comment]
> What exactly is happening? Please answer the following points:
> 
> * is the registration successful? yes
> * is the mail getting sent properly? mail not sent
> * is the user able to login even after this error? won't be able to login since verification mail is not sent
> * was the user already present in db? no

**Comment by harshjohar** [comment]
> > What exactly is happening? Please answer the following points:
> > 
> > * is the registration successful? yes
> > * is the mail getting sent properly? mail not sent
> > * is the user able to login even after this error? won't be able to login since verification mail is not sent
> > * was the user already present in db? no

Alright, will look into this issue asap

**Comment by harshjohar** [comment]
meanwhile, @aadityavvij can use postman to verify his user and start working on #128 ig

**Comment by harasees-singh** [comment]
I think the issue is that I don't have not defined the env var NODEMAILER_EMAIL and NODEMAILER_PW. However the error pop up fails to communicate this issue in case this indeed is the issue

**Comment by harshjohar** [comment]
Yes, just checked this is the issue. Basically, but we dont need this error handling on prod, because the env vars will always be present there. We can just ask developers to read the `README.md` and follow all instructions properly.

**Comment by harshjohar** [comment]
<img width="863" alt="Screenshot 2023-11-13 at 6 00 36 PM" src="https://github.com/PEC-CSS/website/assets/50266759/fcd44939-ebd4-4b34-b590-ed97129608e4">
