### ISSUE TITLE
Event Calender

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/website#146]
- When unlogged-in click:
![image](https://github.com/PEC-CSS/website/assets/75680424/2c064b74-e5f4-4bcc-8804-e591458c6cbc)

![image](https://github.com/PEC-CSS/website/assets/75680424/95de09ac-cf65-442d-929e-a0a48904486c)

**Comment by harasees-singh** [comment]
please add more details, unable to repro

**Comment by Ishwarendra** [comment]
Someone fixed it
