### ISSUE TITLE
Get trending

### ISSUE THREAD

**Issue by harshjohar** [PEC-CSS/website#32]
Fetch data from google sheet
- branch wise filter
- pick top 3 

> Socials will update the google sheet using google forms

**Comment by ken1000minus7** [comment]
For reference
https://github.com/PEC-CSS/PWoC/blob/main/utils/spreadsheet.ts

**Comment by harshjohar** [comment]
For reference

https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication?id=service-account
