### ISSUE TITLE
Convert images to png

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/website#81]
- Find all images in assets. Convert it into png using any editor (online or offline)
- Fix the image extension in code (wherever it is used). 
- Mainly problem is in `constants/team.ts` where photos of core members are added.
- **Do not change** the name of file, change extensions only. Keep both old `jpg` as well the new `png` in the assets.

**Comment by ItsPranavz** [comment]
Can I have this one 🥲

**Comment by GURMEHAR-PEC** [comment]
can i have this one? 😂

**Comment by ItsPranavz** [comment]
:redeyes:

**Comment by Ishwarendra** [comment]
@ItsPranavz assigning you this one.

**Comment by ItsPranavz** [comment]
Done for all jpg files and adjusted code, kept initial files as it is just added the new png files and changed the file extensions in code. Just one question though do we need to do the same for svg files? Only did for jpg...

**Comment by Ishwarendra** [comment]
@ItsPranavz only for jpg and jpeg.
