### ISSUE TITLE
Create event ui

### ISSUE THREAD

**Issue by harshjohar** [PEC-CSS/website#83]
Make a dialog pop up to create new events
- this should be visible to users who have role >= EB
- Location of this pop up will the events page inside the dashboard
- Button at top right of page to open this dialog
- API to be consumed [api](https://documenter.getpostman.com/view/25385933/2s9Xy2NBXm#64cd08a3-12d6-455f-9882-a416fd318041)

**Comment by ken1000minus7** [comment]
@PriyankaSoni2004 curl for create event (the documentation isn't updated yet)
```curl
curl --location 'http://localhost:8080/v1/events' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJva0BnbWFpbC5jb20iLCJleHAiOjE2OTcwNDEzMzQsImlhdCI6MTY5NDQ0OTMzNH0.xEkfRJeAzjQEvK13FvwzsJyYZsKIN4VPB4Mt4koOPXA' \
--header 'Content-Type: application/json' \
--data '{
    "title": "dummy event grfdgdfgdf",
    "startDate": "2023-08-06T00:00:00.000",
    "endDate": "2023-08-06T00:00:00.000",
    "description": "dummy text details",
    "branch": "WIT",
    "venue": "l21"
}'
```
