### ISSUE TITLE
End event UI

### ISSUE THREAD

**Issue by harshjohar** [PEC-CSS/website#84]
Inside the dashboard events page, when user click on any event. A page containing all details of event should open up.

If that event is already "ended" (a flag), the show the details.

Otherwise, display a form with the end event api details and call a POST API.

**Comment by harshjohar** [comment]
@ken1000minus7 share the cURL here for this api

**Comment by ken1000minus7** [comment]
Create event
```curl
curl --location 'http://localhost:8080/v1/events' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJva0BnbWFpbC5jb20iLCJleHAiOjE2OTcwNDEzMzQsImlhdCI6MTY5NDQ0OTMzNH0.xEkfRJeAzjQEvK13FvwzsJyYZsKIN4VPB4Mt4koOPXA' \
--header 'Content-Type: application/json' \
--data '{
    "title": "dummy event grfdgdfgdf",
    "startDate": "2023-08-06T00:00:00.000",
    "endDate": "2023-08-06T00:00:00.000",
    "description": "dummy text details",
    "branch": "WIT",
    "venue": "l21"
}'
```

End event
```curl
curl --location 'http://localhost:8080/v1/events/1/end' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJva0BnbWFpbC5jb20iLCJleHAiOjE2OTcwNDEzMzQsImlhdCI6MTY5NDQ0OTMzNH0.xEkfRJeAzjQEvK13FvwzsJyYZsKIN4VPB4Mt4koOPXA' \
--data-raw '{
    "contributors": ["ok@gmail.com"],
    "publicity": ["ok@gmail.com"],
    "participants": ["harshpreetsinghjohar.btcse20@pec.edu.in"]
}'
```
there also three optional fields
- `contributorXp` (default is 5) 
- `publicityXp` (default is 2)
- `participantXp` (default is 1)

**Comment by ken1000minus7** [comment]
Collect data as following
- contributors in list
- participants in csv (convert to list)
- publicity in list
- rest details in form

**Comment by harasees-singh** [comment]
how are we planning to take input of contributors or publicity ? We cannot expect the user to type in the usernames themselves. Spelling errors are unavoidable.

**Comment by harshjohar** [comment]
After discussion, it is clear ig 👍
