### ISSUE TITLE
Leaderboard 

### ISSUE THREAD

**Issue by harshjohar** [PEC-CSS/website#85]
Fix the leaderboard on homepage and leaderboard page (after logging in)
- consume the leaderboard api
- display users in a list
- show only those users who have xp > 0

**Comment by anshRS** [comment]
I am interested in doing it.

**Comment by anshRS** [comment]
Hi @harshjohar,

I've been assigned the task of fixing the leaderboard on the homepage and leaderboard page, which involves consuming the leaderboard API and displaying users with XP > 0. To ensure a smooth development process, could you please provide the following details:

1. API Endpoint.
2. Authentication Requirements.
3. Specific XP Criteria for Filtering Users.
4. Error Handling Requirements.

This information will help me get started and deliver the feature effectively. Thank you!

Best regards,
Ansh Raj Sharma

**Comment by harshjohar** [comment]
Hi @anshRS 

Here are the details you asked to "ensure smooth development"
- Api : /users/leaderboard GET
- Authentication: Just a bearer token of any role
- no xp criteria, just sort on basis of xp
