### ISSUE TITLE
Update scrollbar

### ISSUE THREAD

**Issue by Ishwarendra** [PEC-CSS/website#90]
- Current Scrollbar is the default scrollbar
    - ![image](https://github.com/PEC-CSS/website/assets/75680424/53abe6d1-b5c7-4a2c-a9cc-a714ea0b3d85)
- Update it. Make the corner smooth like shown below:
    - ![image](https://github.com/PEC-CSS/website/assets/75680424/e8be65a4-7c57-4f23-9f3b-54f44b3c6780)

**Comment by ItsPranavz** [comment]
Can me do it? I having experience with this. 🥺
