### ISSUE TITLE
Add a mechanism to return to home from dashboard

### ISSUE THREAD

**Issue by ken1000minus7** [PEC-CSS/website#93]
Will hv to decide how we need to do this, like hv a button or something else, and where exactly to keep the button

**Comment by harshjohar** [comment]
<img width="248" alt="Screenshot 2023-09-11 at 11 53 54 PM" src="https://github.com/PEC-CSS/website/assets/50266759/e772b85f-2070-45d8-add3-aa547f65a927">

Can add another tab here, called "Explore" just before logout, and it will route to '/'

**Comment by ken1000minus7** [comment]
Lgtm

**Comment by harshjohar** [comment]
@harasees-singh do this as well, just two lines of code

**Comment by harasees-singh** [comment]
the overall outlook doesn't fit in as initially we have a navbar at the top but once we login we get a navbar to the left. Even if we enable users to route back to '/' it would still look very asymmetric

**Comment by harshjohar** [comment]
You can add a full page animation, just like in https://pecfest.org
