### ISSUE TITLE
Stitch events to Events API

### ISSUE THREAD

**Issue by harshjohar** [PEC-CSS/website#97]
Do this after `Create event` fully done and deployed

**Comment by harasees-singh** [comment]
need this before solving #84

**Comment by harasees-singh** [comment]
@harshjohar please ping me once this issue is closed

**Comment by harshjohar** [comment]
Why would u close this issue? @harasees-singh

**Comment by harshjohar** [comment]
Shall be completed by 11/14/23

**Comment by harasees-singh** [comment]
> Why would u close this issue? @harasees-singh 

Misclick
